// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: base_point.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BasePointService_SetBasePoint_FullMethodName = "/pb.BasePointService/SetBasePoint"
	BasePointService_GetBasePoint_FullMethodName = "/pb.BasePointService/GetBasePoint"
)

// BasePointServiceClient is the client API for BasePointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasePointServiceClient interface {
	// 기준점 설정 / 변경
	SetBasePoint(ctx context.Context, in *SetBasePointRequest, opts ...grpc.CallOption) (*SetBasePointResponse, error)
	// 기준점 조회
	GetBasePoint(ctx context.Context, in *GetBasePointRequest, opts ...grpc.CallOption) (*GetBasePointResponse, error)
}

type basePointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBasePointServiceClient(cc grpc.ClientConnInterface) BasePointServiceClient {
	return &basePointServiceClient{cc}
}

func (c *basePointServiceClient) SetBasePoint(ctx context.Context, in *SetBasePointRequest, opts ...grpc.CallOption) (*SetBasePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBasePointResponse)
	err := c.cc.Invoke(ctx, BasePointService_SetBasePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *basePointServiceClient) GetBasePoint(ctx context.Context, in *GetBasePointRequest, opts ...grpc.CallOption) (*GetBasePointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBasePointResponse)
	err := c.cc.Invoke(ctx, BasePointService_GetBasePoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasePointServiceServer is the server API for BasePointService service.
// All implementations must embed UnimplementedBasePointServiceServer
// for forward compatibility.
type BasePointServiceServer interface {
	// 기준점 설정 / 변경
	SetBasePoint(context.Context, *SetBasePointRequest) (*SetBasePointResponse, error)
	// 기준점 조회
	GetBasePoint(context.Context, *GetBasePointRequest) (*GetBasePointResponse, error)
	mustEmbedUnimplementedBasePointServiceServer()
}

// UnimplementedBasePointServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBasePointServiceServer struct{}

func (UnimplementedBasePointServiceServer) SetBasePoint(context.Context, *SetBasePointRequest) (*SetBasePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBasePoint not implemented")
}
func (UnimplementedBasePointServiceServer) GetBasePoint(context.Context, *GetBasePointRequest) (*GetBasePointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBasePoint not implemented")
}
func (UnimplementedBasePointServiceServer) mustEmbedUnimplementedBasePointServiceServer() {}
func (UnimplementedBasePointServiceServer) testEmbeddedByValue()                          {}

// UnsafeBasePointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasePointServiceServer will
// result in compilation errors.
type UnsafeBasePointServiceServer interface {
	mustEmbedUnimplementedBasePointServiceServer()
}

func RegisterBasePointServiceServer(s grpc.ServiceRegistrar, srv BasePointServiceServer) {
	// If the following call panics, it indicates UnimplementedBasePointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BasePointService_ServiceDesc, srv)
}

func _BasePointService_SetBasePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBasePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasePointServiceServer).SetBasePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasePointService_SetBasePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasePointServiceServer).SetBasePoint(ctx, req.(*SetBasePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BasePointService_GetBasePoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBasePointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasePointServiceServer).GetBasePoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BasePointService_GetBasePoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasePointServiceServer).GetBasePoint(ctx, req.(*GetBasePointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasePointService_ServiceDesc is the grpc.ServiceDesc for BasePointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasePointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BasePointService",
	HandlerType: (*BasePointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBasePoint",
			Handler:    _BasePointService_SetBasePoint_Handler,
		},
		{
			MethodName: "GetBasePoint",
			Handler:    _BasePointService_GetBasePoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base_point.proto",
}
