// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: base_point.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasePointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasePointRequest) Reset() {
	*x = GetBasePointRequest{}
	mi := &file_base_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasePointRequest) ProtoMessage() {}

func (x *GetBasePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasePointRequest.ProtoReflect.Descriptor instead.
func (*GetBasePointRequest) Descriptor() ([]byte, []int) {
	return file_base_point_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasePointRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetBasePointRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetBasePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	LinkId        string                 `protobuf:"bytes,3,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasePointResponse) Reset() {
	*x = GetBasePointResponse{}
	mi := &file_base_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasePointResponse) ProtoMessage() {}

func (x *GetBasePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasePointResponse.ProtoReflect.Descriptor instead.
func (*GetBasePointResponse) Descriptor() ([]byte, []int) {
	return file_base_point_proto_rawDescGZIP(), []int{1}
}

func (x *GetBasePointResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBasePointResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetBasePointResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetBasePointResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetBasePointResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetBasePointResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetBasePointResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SetBasePointRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MeetingId string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	// 둘 중 하나 이상 필요
	Latitude      float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	LinkId        string  `protobuf:"bytes,4,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBasePointRequest) Reset() {
	*x = SetBasePointRequest{}
	mi := &file_base_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBasePointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBasePointRequest) ProtoMessage() {}

func (x *SetBasePointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBasePointRequest.ProtoReflect.Descriptor instead.
func (*SetBasePointRequest) Descriptor() ([]byte, []int) {
	return file_base_point_proto_rawDescGZIP(), []int{2}
}

func (x *SetBasePointRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SetBasePointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetBasePointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SetBasePointRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type SetBasePointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	LinkId        string                 `protobuf:"bytes,4,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBasePointResponse) Reset() {
	*x = SetBasePointResponse{}
	mi := &file_base_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBasePointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBasePointResponse) ProtoMessage() {}

func (x *SetBasePointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBasePointResponse.ProtoReflect.Descriptor instead.
func (*SetBasePointResponse) Descriptor() ([]byte, []int) {
	return file_base_point_proto_rawDescGZIP(), []int{3}
}

func (x *SetBasePointResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SetBasePointResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetBasePointResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SetBasePointResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

var File_base_point_proto protoreflect.FileDescriptor

const file_base_point_proto_rawDesc = "" +
	"\n" +
	"\x10base_point.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"P\n" +
	"\x13GetBasePointRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\xca\x01\n" +
	"\x14GetBasePointResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12\x17\n" +
	"\alink_id\x18\x03 \x01(\tR\x06linkId\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\"\x87\x01\n" +
	"\x13SetBasePointRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x17\n" +
	"\alink_id\x18\x04 \x01(\tR\x06linkId\"\x88\x01\n" +
	"\x14SetBasePointResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x17\n" +
	"\alink_id\x18\x04 \x01(\tR\x06linkId2\xf2\x01\n" +
	"\x10BasePointService\x12i\n" +
	"\fSetBasePoint\x12\x17.pb.SetBasePointRequest\x1a\x18.pb.SetBasePointResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/meetings/base-point\x12s\n" +
	"\fGetBasePoint\x12\x17.pb.GetBasePointRequest\x1a\x18.pb.GetBasePointResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/meetings/{meeting_id}/base-pointB\x17Z\x15WEPLAN/internal/pb;pbb\x06proto3"

var (
	file_base_point_proto_rawDescOnce sync.Once
	file_base_point_proto_rawDescData []byte
)

func file_base_point_proto_rawDescGZIP() []byte {
	file_base_point_proto_rawDescOnce.Do(func() {
		file_base_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_point_proto_rawDesc), len(file_base_point_proto_rawDesc)))
	})
	return file_base_point_proto_rawDescData
}

var file_base_point_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_base_point_proto_goTypes = []any{
	(*GetBasePointRequest)(nil),  // 0: pb.GetBasePointRequest
	(*GetBasePointResponse)(nil), // 1: pb.GetBasePointResponse
	(*SetBasePointRequest)(nil),  // 2: pb.SetBasePointRequest
	(*SetBasePointResponse)(nil), // 3: pb.SetBasePointResponse
}
var file_base_point_proto_depIdxs = []int32{
	2, // 0: pb.BasePointService.SetBasePoint:input_type -> pb.SetBasePointRequest
	0, // 1: pb.BasePointService.GetBasePoint:input_type -> pb.GetBasePointRequest
	3, // 2: pb.BasePointService.SetBasePoint:output_type -> pb.SetBasePointResponse
	1, // 3: pb.BasePointService.GetBasePoint:output_type -> pb.GetBasePointResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_point_proto_init() }
func file_base_point_proto_init() {
	if File_base_point_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_point_proto_rawDesc), len(file_base_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_point_proto_goTypes,
		DependencyIndexes: file_base_point_proto_depIdxs,
		MessageInfos:      file_base_point_proto_msgTypes,
	}.Build()
	File_base_point_proto = out.File
	file_base_point_proto_goTypes = nil
	file_base_point_proto_depIdxs = nil
}
