// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: budget.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BudgetService_CreateItem_FullMethodName   = "/pb.BudgetService/CreateItem"
	BudgetService_ListItems_FullMethodName    = "/pb.BudgetService/ListItems"
	BudgetService_CreateLeader_FullMethodName = "/pb.BudgetService/CreateLeader"
	BudgetService_GetLeader_FullMethodName    = "/pb.BudgetService/GetLeader"
	BudgetService_GetSummary_FullMethodName   = "/pb.BudgetService/GetSummary"
	BudgetService_UDBudgetItem_FullMethodName = "/pb.BudgetService/UDBudgetItem"
)

// BudgetServiceClient is the client API for BudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BudgetServiceClient interface {
	// 예산 항목 추가
	CreateItem(ctx context.Context, in *CreateBudgetItemRequest, opts ...grpc.CallOption) (*CreateBudgetItemResponse, error)
	// 예산 항목 목록
	ListItems(ctx context.Context, in *ListBudgetItemsRequest, opts ...grpc.CallOption) (*ListBudgetItemsResponse, error)
	// 총무 추가 및 변경
	CreateLeader(ctx context.Context, in *CreateBudgetLeaderRequest, opts ...grpc.CallOption) (*CreateBudgetLeaderResponse, error)
	// 총무 조회
	GetLeader(ctx context.Context, in *GetBudgetLeaderRequest, opts ...grpc.CallOption) (*GetBudgetLeaderResponse, error)
	// 예산 요약
	GetSummary(ctx context.Context, in *GetBudgetSummaryRequest, opts ...grpc.CallOption) (*GetBudgetSummaryResponse, error)
	// ✅ Update/Delete 단일 RPC (신규)
	UDBudgetItem(ctx context.Context, in *UDBudgetItemRequest, opts ...grpc.CallOption) (*UDBudgetItemResponse, error)
}

type budgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetServiceClient(cc grpc.ClientConnInterface) BudgetServiceClient {
	return &budgetServiceClient{cc}
}

func (c *budgetServiceClient) CreateItem(ctx context.Context, in *CreateBudgetItemRequest, opts ...grpc.CallOption) (*CreateBudgetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBudgetItemResponse)
	err := c.cc.Invoke(ctx, BudgetService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) ListItems(ctx context.Context, in *ListBudgetItemsRequest, opts ...grpc.CallOption) (*ListBudgetItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBudgetItemsResponse)
	err := c.cc.Invoke(ctx, BudgetService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) CreateLeader(ctx context.Context, in *CreateBudgetLeaderRequest, opts ...grpc.CallOption) (*CreateBudgetLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBudgetLeaderResponse)
	err := c.cc.Invoke(ctx, BudgetService_CreateLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) GetLeader(ctx context.Context, in *GetBudgetLeaderRequest, opts ...grpc.CallOption) (*GetBudgetLeaderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetLeaderResponse)
	err := c.cc.Invoke(ctx, BudgetService_GetLeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) GetSummary(ctx context.Context, in *GetBudgetSummaryRequest, opts ...grpc.CallOption) (*GetBudgetSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetSummaryResponse)
	err := c.cc.Invoke(ctx, BudgetService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetServiceClient) UDBudgetItem(ctx context.Context, in *UDBudgetItemRequest, opts ...grpc.CallOption) (*UDBudgetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UDBudgetItemResponse)
	err := c.cc.Invoke(ctx, BudgetService_UDBudgetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetServiceServer is the server API for BudgetService service.
// All implementations must embed UnimplementedBudgetServiceServer
// for forward compatibility.
type BudgetServiceServer interface {
	// 예산 항목 추가
	CreateItem(context.Context, *CreateBudgetItemRequest) (*CreateBudgetItemResponse, error)
	// 예산 항목 목록
	ListItems(context.Context, *ListBudgetItemsRequest) (*ListBudgetItemsResponse, error)
	// 총무 추가 및 변경
	CreateLeader(context.Context, *CreateBudgetLeaderRequest) (*CreateBudgetLeaderResponse, error)
	// 총무 조회
	GetLeader(context.Context, *GetBudgetLeaderRequest) (*GetBudgetLeaderResponse, error)
	// 예산 요약
	GetSummary(context.Context, *GetBudgetSummaryRequest) (*GetBudgetSummaryResponse, error)
	// ✅ Update/Delete 단일 RPC (신규)
	UDBudgetItem(context.Context, *UDBudgetItemRequest) (*UDBudgetItemResponse, error)
	mustEmbedUnimplementedBudgetServiceServer()
}

// UnimplementedBudgetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBudgetServiceServer struct{}

func (UnimplementedBudgetServiceServer) CreateItem(context.Context, *CreateBudgetItemRequest) (*CreateBudgetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedBudgetServiceServer) ListItems(context.Context, *ListBudgetItemsRequest) (*ListBudgetItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedBudgetServiceServer) CreateLeader(context.Context, *CreateBudgetLeaderRequest) (*CreateBudgetLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLeader not implemented")
}
func (UnimplementedBudgetServiceServer) GetLeader(context.Context, *GetBudgetLeaderRequest) (*GetBudgetLeaderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeader not implemented")
}
func (UnimplementedBudgetServiceServer) GetSummary(context.Context, *GetBudgetSummaryRequest) (*GetBudgetSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedBudgetServiceServer) UDBudgetItem(context.Context, *UDBudgetItemRequest) (*UDBudgetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UDBudgetItem not implemented")
}
func (UnimplementedBudgetServiceServer) mustEmbedUnimplementedBudgetServiceServer() {}
func (UnimplementedBudgetServiceServer) testEmbeddedByValue()                       {}

// UnsafeBudgetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BudgetServiceServer will
// result in compilation errors.
type UnsafeBudgetServiceServer interface {
	mustEmbedUnimplementedBudgetServiceServer()
}

func RegisterBudgetServiceServer(s grpc.ServiceRegistrar, srv BudgetServiceServer) {
	// If the following call panics, it indicates UnimplementedBudgetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BudgetService_ServiceDesc, srv)
}

func _BudgetService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).CreateItem(ctx, req.(*CreateBudgetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBudgetItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).ListItems(ctx, req.(*ListBudgetItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_CreateLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).CreateLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_CreateLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).CreateLeader(ctx, req.(*CreateBudgetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_GetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).GetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_GetLeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).GetLeader(ctx, req.(*GetBudgetLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).GetSummary(ctx, req.(*GetBudgetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetService_UDBudgetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UDBudgetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).UDBudgetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BudgetService_UDBudgetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).UDBudgetItem(ctx, req.(*UDBudgetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BudgetService_ServiceDesc is the grpc.ServiceDesc for BudgetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BudgetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BudgetService",
	HandlerType: (*BudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _BudgetService_CreateItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _BudgetService_ListItems_Handler,
		},
		{
			MethodName: "CreateLeader",
			Handler:    _BudgetService_CreateLeader_Handler,
		},
		{
			MethodName: "GetLeader",
			Handler:    _BudgetService_GetLeader_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _BudgetService_GetSummary_Handler,
		},
		{
			MethodName: "UDBudgetItem",
			Handler:    _BudgetService_UDBudgetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "budget.proto",
}
