// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: budget.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBudgetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetItemRequest) Reset() {
	*x = CreateBudgetItemRequest{}
	mi := &file_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetItemRequest) ProtoMessage() {}

func (x *CreateBudgetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetItemRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetItemRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBudgetItemRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CreateBudgetItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBudgetItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBudgetItemRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateBudgetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetItemResponse) Reset() {
	*x = CreateBudgetItemResponse{}
	mi := &file_budget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetItemResponse) ProtoMessage() {}

func (x *CreateBudgetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetItemResponse.ProtoReflect.Descriptor instead.
func (*CreateBudgetItemResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBudgetItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ListBudgetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetItemsRequest) Reset() {
	*x = ListBudgetItemsRequest{}
	mi := &file_budget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetItemsRequest) ProtoMessage() {}

func (x *ListBudgetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetItemsRequest.ProtoReflect.Descriptor instead.
func (*ListBudgetItemsRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{2}
}

func (x *ListBudgetItemsRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type BudgetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Amount        int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetItem) Reset() {
	*x = BudgetItem{}
	mi := &file_budget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetItem) ProtoMessage() {}

func (x *BudgetItem) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetItem.ProtoReflect.Descriptor instead.
func (*BudgetItem) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetItem) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *BudgetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BudgetItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BudgetItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ListBudgetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BudgetItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetItemsResponse) Reset() {
	*x = ListBudgetItemsResponse{}
	mi := &file_budget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetItemsResponse) ProtoMessage() {}

func (x *ListBudgetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetItemsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetItemsResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{4}
}

func (x *ListBudgetItemsResponse) GetItems() []*BudgetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetBudgetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	MemberCount   int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetSummaryRequest) Reset() {
	*x = GetBudgetSummaryRequest{}
	mi := &file_budget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetSummaryRequest) ProtoMessage() {}

func (x *GetBudgetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{5}
}

func (x *GetBudgetSummaryRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetBudgetSummaryRequest) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type GetBudgetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	MemberCount   int32                  `protobuf:"varint,3,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	PerPerson     int32                  `protobuf:"varint,4,opt,name=per_person,json=perPerson,proto3" json:"per_person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetSummaryResponse) Reset() {
	*x = GetBudgetSummaryResponse{}
	mi := &file_budget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetSummaryResponse) ProtoMessage() {}

func (x *GetBudgetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{6}
}

func (x *GetBudgetSummaryResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetBudgetSummaryResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetBudgetSummaryResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GetBudgetSummaryResponse) GetPerPerson() int32 {
	if x != nil {
		return x.PerPerson
	}
	return 0
}

type BudgetLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank          string                 `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Acount        string                 `protobuf:"bytes,4,opt,name=acount,proto3" json:"acount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetLeader) Reset() {
	*x = BudgetLeader{}
	mi := &file_budget_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetLeader) ProtoMessage() {}

func (x *BudgetLeader) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetLeader.ProtoReflect.Descriptor instead.
func (*BudgetLeader) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{7}
}

func (x *BudgetLeader) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *BudgetLeader) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BudgetLeader) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *BudgetLeader) GetAcount() string {
	if x != nil {
		return x.Acount
	}
	return ""
}

type CreateBudgetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bank          string                 `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Acount        string                 `protobuf:"bytes,4,opt,name=acount,proto3" json:"acount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetLeaderRequest) Reset() {
	*x = CreateBudgetLeaderRequest{}
	mi := &file_budget_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetLeaderRequest) ProtoMessage() {}

func (x *CreateBudgetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetLeaderRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBudgetLeaderRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CreateBudgetLeaderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBudgetLeaderRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CreateBudgetLeaderRequest) GetAcount() string {
	if x != nil {
		return x.Acount
	}
	return ""
}

type CreateBudgetLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetLeaderResponse) Reset() {
	*x = CreateBudgetLeaderResponse{}
	mi := &file_budget_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetLeaderResponse) ProtoMessage() {}

func (x *CreateBudgetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetLeaderResponse.ProtoReflect.Descriptor instead.
func (*CreateBudgetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBudgetLeaderResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetBudgetLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetLeaderRequest) Reset() {
	*x = GetBudgetLeaderRequest{}
	mi := &file_budget_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetLeaderRequest) ProtoMessage() {}

func (x *GetBudgetLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetLeaderRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetLeaderRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{10}
}

func (x *GetBudgetLeaderRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetBudgetLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BudgetLeader        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetLeaderResponse) Reset() {
	*x = GetBudgetLeaderResponse{}
	mi := &file_budget_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetLeaderResponse) ProtoMessage() {}

func (x *GetBudgetLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetLeaderResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetLeaderResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{11}
}

func (x *GetBudgetLeaderResponse) GetItems() []*BudgetLeader {
	if x != nil {
		return x.Items
	}
	return nil
}

type UDBudgetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"` // ✅ 필수: WS room key
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                // ✅ 필수: budget_item_id
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`                                // ✅ 필수: "u" | "d"
	Fields        *UDBudgetItemFields    `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`                        // op=="u"에서만
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDBudgetItemRequest) Reset() {
	*x = UDBudgetItemRequest{}
	mi := &file_budget_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDBudgetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDBudgetItemRequest) ProtoMessage() {}

func (x *UDBudgetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDBudgetItemRequest.ProtoReflect.Descriptor instead.
func (*UDBudgetItemRequest) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{12}
}

func (x *UDBudgetItemRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *UDBudgetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDBudgetItemRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDBudgetItemRequest) GetFields() *UDBudgetItemFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UDBudgetItemFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDBudgetItemFields) Reset() {
	*x = UDBudgetItemFields{}
	mi := &file_budget_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDBudgetItemFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDBudgetItemFields) ProtoMessage() {}

func (x *UDBudgetItemFields) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDBudgetItemFields.ProtoReflect.Descriptor instead.
func (*UDBudgetItemFields) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{13}
}

func (x *UDBudgetItemFields) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UDBudgetItemFields) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UDBudgetItemFields) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UDBudgetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	Item          *BudgetItem            `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"` // op=="u"에서만
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDBudgetItemResponse) Reset() {
	*x = UDBudgetItemResponse{}
	mi := &file_budget_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDBudgetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDBudgetItemResponse) ProtoMessage() {}

func (x *UDBudgetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDBudgetItemResponse.ProtoReflect.Descriptor instead.
func (*UDBudgetItemResponse) Descriptor() ([]byte, []int) {
	return file_budget_proto_rawDescGZIP(), []int{14}
}

func (x *UDBudgetItemResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *UDBudgetItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDBudgetItemResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDBudgetItemResponse) GetItem() *BudgetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_budget_proto protoreflect.FileDescriptor

const file_budget_proto_rawDesc = "" +
	"\n" +
	"\fbudget.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\x80\x01\n" +
	"\x17CreateBudgetItemRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\"3\n" +
	"\x18CreateBudgetItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"7\n" +
	"\x16ListBudgetItemsRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\"\x83\x01\n" +
	"\n" +
	"BudgetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\"?\n" +
	"\x17ListBudgetItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.pb.BudgetItemR\x05items\"[\n" +
	"\x17GetBudgetSummaryRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12!\n" +
	"\fmember_count\x18\x02 \x01(\x05R\vmemberCount\"\x9e\x01\n" +
	"\x18GetBudgetSummaryResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x05R\vtotalAmount\x12!\n" +
	"\fmember_count\x18\x03 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"per_person\x18\x04 \x01(\x05R\tperPerson\"r\n" +
	"\fBudgetLeader\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\tR\x04bank\x12\x16\n" +
	"\x06acount\x18\x04 \x01(\tR\x06acount\"\x7f\n" +
	"\x19CreateBudgetLeaderRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\tR\x04bank\x12\x16\n" +
	"\x06acount\x18\x04 \x01(\tR\x06acount\";\n" +
	"\x1aCreateBudgetLeaderResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\"7\n" +
	"\x16GetBudgetLeaderRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\"A\n" +
	"\x17GetBudgetLeaderResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.pb.BudgetLeaderR\x05items\"\x84\x01\n" +
	"\x13UDBudgetItemRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12.\n" +
	"\x06fields\x18\x04 \x01(\v2\x16.pb.UDBudgetItemFieldsR\x06fields\"\\\n" +
	"\x12UDBudgetItemFields\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"y\n" +
	"\x14UDBudgetItemResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\"\n" +
	"\x04item\x18\x04 \x01(\v2\x0e.pb.BudgetItemR\x04item2\xd1\x05\n" +
	"\rBudgetService\x12q\n" +
	"\n" +
	"CreateItem\x12\x1b.pb.CreateBudgetItemRequest\x1a\x1c.pb.CreateBudgetItemResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/meetings/budget/items\x12x\n" +
	"\tListItems\x12\x1a.pb.ListBudgetItemsRequest\x1a\x1b.pb.ListBudgetItemsResponse\"2\x82\xd3\xe4\x93\x02,\x12*/api/v1/meetings/{meeting_id}/budget/items\x12x\n" +
	"\fCreateLeader\x12\x1d.pb.CreateBudgetLeaderRequest\x1a\x1e.pb.CreateBudgetLeaderResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/meetings/budget/leader\x12y\n" +
	"\tGetLeader\x12\x1a.pb.GetBudgetLeaderRequest\x1a\x1b.pb.GetBudgetLeaderResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/meetings/budget/leader/{meeting_id}\x12}\n" +
	"\n" +
	"GetSummary\x12\x1b.pb.GetBudgetSummaryRequest\x1a\x1c.pb.GetBudgetSummaryResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/meetings/{meeting_id}/budget/summary\x12_\n" +
	"\fUDBudgetItem\x12\x17.pb.UDBudgetItemRequest\x1a\x18.pb.UDBudgetItemResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/budget/udB\x17Z\x15WEPLAN/internal/pb;pbb\x06proto3"

var (
	file_budget_proto_rawDescOnce sync.Once
	file_budget_proto_rawDescData []byte
)

func file_budget_proto_rawDescGZIP() []byte {
	file_budget_proto_rawDescOnce.Do(func() {
		file_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_proto_rawDesc), len(file_budget_proto_rawDesc)))
	})
	return file_budget_proto_rawDescData
}

var file_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_budget_proto_goTypes = []any{
	(*CreateBudgetItemRequest)(nil),    // 0: pb.CreateBudgetItemRequest
	(*CreateBudgetItemResponse)(nil),   // 1: pb.CreateBudgetItemResponse
	(*ListBudgetItemsRequest)(nil),     // 2: pb.ListBudgetItemsRequest
	(*BudgetItem)(nil),                 // 3: pb.BudgetItem
	(*ListBudgetItemsResponse)(nil),    // 4: pb.ListBudgetItemsResponse
	(*GetBudgetSummaryRequest)(nil),    // 5: pb.GetBudgetSummaryRequest
	(*GetBudgetSummaryResponse)(nil),   // 6: pb.GetBudgetSummaryResponse
	(*BudgetLeader)(nil),               // 7: pb.BudgetLeader
	(*CreateBudgetLeaderRequest)(nil),  // 8: pb.CreateBudgetLeaderRequest
	(*CreateBudgetLeaderResponse)(nil), // 9: pb.CreateBudgetLeaderResponse
	(*GetBudgetLeaderRequest)(nil),     // 10: pb.GetBudgetLeaderRequest
	(*GetBudgetLeaderResponse)(nil),    // 11: pb.GetBudgetLeaderResponse
	(*UDBudgetItemRequest)(nil),        // 12: pb.UDBudgetItemRequest
	(*UDBudgetItemFields)(nil),         // 13: pb.UDBudgetItemFields
	(*UDBudgetItemResponse)(nil),       // 14: pb.UDBudgetItemResponse
}
var file_budget_proto_depIdxs = []int32{
	3,  // 0: pb.ListBudgetItemsResponse.items:type_name -> pb.BudgetItem
	7,  // 1: pb.GetBudgetLeaderResponse.items:type_name -> pb.BudgetLeader
	13, // 2: pb.UDBudgetItemRequest.fields:type_name -> pb.UDBudgetItemFields
	3,  // 3: pb.UDBudgetItemResponse.item:type_name -> pb.BudgetItem
	0,  // 4: pb.BudgetService.CreateItem:input_type -> pb.CreateBudgetItemRequest
	2,  // 5: pb.BudgetService.ListItems:input_type -> pb.ListBudgetItemsRequest
	8,  // 6: pb.BudgetService.CreateLeader:input_type -> pb.CreateBudgetLeaderRequest
	10, // 7: pb.BudgetService.GetLeader:input_type -> pb.GetBudgetLeaderRequest
	5,  // 8: pb.BudgetService.GetSummary:input_type -> pb.GetBudgetSummaryRequest
	12, // 9: pb.BudgetService.UDBudgetItem:input_type -> pb.UDBudgetItemRequest
	1,  // 10: pb.BudgetService.CreateItem:output_type -> pb.CreateBudgetItemResponse
	4,  // 11: pb.BudgetService.ListItems:output_type -> pb.ListBudgetItemsResponse
	9,  // 12: pb.BudgetService.CreateLeader:output_type -> pb.CreateBudgetLeaderResponse
	11, // 13: pb.BudgetService.GetLeader:output_type -> pb.GetBudgetLeaderResponse
	6,  // 14: pb.BudgetService.GetSummary:output_type -> pb.GetBudgetSummaryResponse
	14, // 15: pb.BudgetService.UDBudgetItem:output_type -> pb.UDBudgetItemResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_budget_proto_init() }
func file_budget_proto_init() {
	if File_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_proto_rawDesc), len(file_budget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_proto_goTypes,
		DependencyIndexes: file_budget_proto_depIdxs,
		MessageInfos:      file_budget_proto_msgTypes,
	}.Build()
	File_budget_proto = out.File
	file_budget_proto_goTypes = nil
	file_budget_proto_depIdxs = nil
}
