// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dashboard.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	MemberCount   int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"` // N빵 계산용 인원 수
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *GetDashboardRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetDashboardRequest) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type DashboardMeeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // ISO8601 문자열 (RFC3339)
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardMeeting) Reset() {
	*x = DashboardMeeting{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardMeeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardMeeting) ProtoMessage() {}

func (x *DashboardMeeting) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardMeeting.ProtoReflect.Descriptor instead.
func (*DashboardMeeting) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardMeeting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardMeeting) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DashboardMeeting) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DashboardMeeting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DashboardMeeting) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type DashboardLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Memo          string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Rating        float32                `protobuf:"fixed32,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardLink) Reset() {
	*x = DashboardLink{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardLink) ProtoMessage() {}

func (x *DashboardLink) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardLink.ProtoReflect.Descriptor instead.
func (*DashboardLink) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DashboardLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DashboardLink) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *DashboardLink) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DashboardBudgetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardBudgetItem) Reset() {
	*x = DashboardBudgetItem{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardBudgetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardBudgetItem) ProtoMessage() {}

func (x *DashboardBudgetItem) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardBudgetItem.ProtoReflect.Descriptor instead.
func (*DashboardBudgetItem) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardBudgetItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardBudgetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DashboardBudgetItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DashboardBudgetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   int32                  `protobuf:"varint,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	MemberCount   int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	PerPerson     int32                  `protobuf:"varint,3,opt,name=per_person,json=perPerson,proto3" json:"per_person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardBudgetSummary) Reset() {
	*x = DashboardBudgetSummary{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardBudgetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardBudgetSummary) ProtoMessage() {}

func (x *DashboardBudgetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardBudgetSummary.ProtoReflect.Descriptor instead.
func (*DashboardBudgetSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *DashboardBudgetSummary) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *DashboardBudgetSummary) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *DashboardBudgetSummary) GetPerPerson() int32 {
	if x != nil {
		return x.PerPerson
	}
	return 0
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Meeting       *DashboardMeeting       `protobuf:"bytes,1,opt,name=meeting,proto3" json:"meeting,omitempty"`
	Links         []*DashboardLink        `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	BudgetItems   []*DashboardBudgetItem  `protobuf:"bytes,3,rep,name=budget_items,json=budgetItems,proto3" json:"budget_items,omitempty"`
	BudgetSummary *DashboardBudgetSummary `protobuf:"bytes,4,opt,name=budget_summary,json=budgetSummary,proto3" json:"budget_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *GetDashboardResponse) GetMeeting() *DashboardMeeting {
	if x != nil {
		return x.Meeting
	}
	return nil
}

func (x *GetDashboardResponse) GetLinks() []*DashboardLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *GetDashboardResponse) GetBudgetItems() []*DashboardBudgetItem {
	if x != nil {
		return x.BudgetItems
	}
	return nil
}

func (x *GetDashboardResponse) GetBudgetSummary() *DashboardBudgetSummary {
	if x != nil {
		return x.BudgetSummary
	}
	return nil
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"W\n" +
	"\x13GetDashboardRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12!\n" +
	"\fmember_count\x18\x02 \x01(\x05R\vmemberCount\"\x8c\x01\n" +
	"\x10DashboardMeeting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x05 \x01(\tR\tthumbnail\"s\n" +
	"\rDashboardLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x02R\x06rating\"Q\n" +
	"\x13DashboardBudgetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"}\n" +
	"\x16DashboardBudgetSummary\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x05R\vtotalAmount\x12!\n" +
	"\fmember_count\x18\x02 \x01(\x05R\vmemberCount\x12\x1d\n" +
	"\n" +
	"per_person\x18\x03 \x01(\x05R\tperPerson\"\xee\x01\n" +
	"\x14GetDashboardResponse\x12.\n" +
	"\ameeting\x18\x01 \x01(\v2\x14.pb.DashboardMeetingR\ameeting\x12'\n" +
	"\x05links\x18\x02 \x03(\v2\x11.pb.DashboardLinkR\x05links\x12:\n" +
	"\fbudget_items\x18\x03 \x03(\v2\x17.pb.DashboardBudgetItemR\vbudgetItems\x12A\n" +
	"\x0ebudget_summary\x18\x04 \x01(\v2\x1a.pb.DashboardBudgetSummaryR\rbudgetSummary2\x81\x01\n" +
	"\x10DashboardService\x12m\n" +
	"\fGetDashboard\x12\x17.pb.GetDashboardRequest\x1a\x18.pb.GetDashboardResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/api/weplan/dashboard/{meeting_id}B\x14Z\x12WEPLAN/internal/pbb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dashboard_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),    // 0: pb.GetDashboardRequest
	(*DashboardMeeting)(nil),       // 1: pb.DashboardMeeting
	(*DashboardLink)(nil),          // 2: pb.DashboardLink
	(*DashboardBudgetItem)(nil),    // 3: pb.DashboardBudgetItem
	(*DashboardBudgetSummary)(nil), // 4: pb.DashboardBudgetSummary
	(*GetDashboardResponse)(nil),   // 5: pb.GetDashboardResponse
}
var file_dashboard_proto_depIdxs = []int32{
	1, // 0: pb.GetDashboardResponse.meeting:type_name -> pb.DashboardMeeting
	2, // 1: pb.GetDashboardResponse.links:type_name -> pb.DashboardLink
	3, // 2: pb.GetDashboardResponse.budget_items:type_name -> pb.DashboardBudgetItem
	4, // 3: pb.GetDashboardResponse.budget_summary:type_name -> pb.DashboardBudgetSummary
	0, // 4: pb.DashboardService.GetDashboard:input_type -> pb.GetDashboardRequest
	5, // 5: pb.DashboardService.GetDashboard:output_type -> pb.GetDashboardResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
