// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: link.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =======================
// Create/List (기존 + 필드 확장 유지)
// =======================
type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Memo          string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`   // 0이면 미설정으로 해석(서버 규칙)
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"` // 0이면 미설정으로 해석(서버 규칙)
	Images        string                 `protobuf:"bytes,9,opt,name=images,proto3" json:"images,omitempty"`         // JSON string (DB: JSONB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLinkRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *CreateLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLinkRequest) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *CreateLinkRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateLinkRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateLinkRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateLinkRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateLinkRequest) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // 선택: 비어있으면 전체 조회
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{2}
}

func (x *ListLinksRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *ListLinksRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Memo          string                 `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Latitude      float64                `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Images        string                 `protobuf:"bytes,10,opt,name=images,proto3" json:"images,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{3}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Link) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Link) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Link) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Link) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Link) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*Link                `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{4}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// =======================
// Enrich (기존)
// =======================
type EnrichLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichLinkRequest) Reset() {
	*x = EnrichLinkRequest{}
	mi := &file_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLinkRequest) ProtoMessage() {}

func (x *EnrichLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLinkRequest.ProtoReflect.Descriptor instead.
func (*EnrichLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{5}
}

func (x *EnrichLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type EnrichLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichLinkResponse) Reset() {
	*x = EnrichLinkResponse{}
	mi := &file_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichLinkResponse) ProtoMessage() {}

func (x *EnrichLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichLinkResponse.ProtoReflect.Descriptor instead.
func (*EnrichLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichLinkResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EnrichLinkResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *EnrichLinkResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EnrichLinkResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// =======================
// ✅ UD (Update/Delete)
// =======================
type UDLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"` // ✅ 필수: WS room key
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                // ✅ 필수: link_id
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`                                // ✅ 필수: "u" | "d"
	Fields        *UDLinkFields          `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`                        // op=="u"에서만 사용
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDLinkRequest) Reset() {
	*x = UDLinkRequest{}
	mi := &file_link_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDLinkRequest) ProtoMessage() {}

func (x *UDLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDLinkRequest.ProtoReflect.Descriptor instead.
func (*UDLinkRequest) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{7}
}

func (x *UDLinkRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *UDLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDLinkRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDLinkRequest) GetFields() *UDLinkFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UDLinkFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Memo          string                 `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`   // 0이면 무시 규칙(요구사항: 빈/미지정은 건드리지 않음)
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"` // 0이면 무시
	Images        string                 `protobuf:"bytes,8,opt,name=images,proto3" json:"images,omitempty"`         // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDLinkFields) Reset() {
	*x = UDLinkFields{}
	mi := &file_link_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDLinkFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDLinkFields) ProtoMessage() {}

func (x *UDLinkFields) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDLinkFields.ProtoReflect.Descriptor instead.
func (*UDLinkFields) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{8}
}

func (x *UDLinkFields) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UDLinkFields) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UDLinkFields) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *UDLinkFields) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UDLinkFields) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UDLinkFields) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UDLinkFields) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UDLinkFields) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type UDLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	Link          *Link                  `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"` // op=="u"일 때만 채울 수 있음
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDLinkResponse) Reset() {
	*x = UDLinkResponse{}
	mi := &file_link_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDLinkResponse) ProtoMessage() {}

func (x *UDLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDLinkResponse.ProtoReflect.Descriptor instead.
func (*UDLinkResponse) Descriptor() ([]byte, []int) {
	return file_link_proto_rawDescGZIP(), []int{9}
}

func (x *UDLinkResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *UDLinkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDLinkResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

var File_link_proto protoreflect.FileDescriptor

const file_link_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"link.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\xf4\x01\n" +
	"\x11CreateLinkRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06images\x18\t \x01(\tR\x06images\"-\n" +
	"\x12CreateLinkResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\"M\n" +
	"\x10ListLinksRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\xf7\x01\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\tR\x04memo\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06images\x18\n" +
	" \x01(\tR\x06images\"3\n" +
	"\x11ListLinksResponse\x12\x1e\n" +
	"\x05links\x18\x01 \x03(\v2\b.pb.LinkR\x05links\"%\n" +
	"\x11EnrichLinkRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x82\x01\n" +
	"\x12EnrichLinkResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x02 \x01(\tR\tthumbnail\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"x\n" +
	"\rUDLinkRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12(\n" +
	"\x06fields\x18\x04 \x01(\v2\x10.pb.UDLinkFieldsR\x06fields\"\xd0\x01\n" +
	"\fUDLinkFields\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04memo\x18\x03 \x01(\tR\x04memo\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06images\x18\b \x01(\tR\x06images\"m\n" +
	"\x0eUDLinkResponse\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\x1c\n" +
	"\x04link\x18\x04 \x01(\v2\b.pb.LinkR\x04link2\xaf\x02\n" +
	"\vLinkService\x12k\n" +
	"\n" +
	"CreateLink\x12\x15.pb.CreateLinkRequest\x1a\x16.pb.CreateLinkResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/meetings/{meeting_id}/links\x12e\n" +
	"\tListLinks\x12\x14.pb.ListLinksRequest\x1a\x15.pb.ListLinksResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/meetings/{meeting_id}/links\x12L\n" +
	"\x06UDLink\x12\x11.pb.UDLinkRequest\x1a\x12.pb.UDLinkResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/links/udB\x17Z\x15WEPLAN/internal/pb;pbb\x06proto3"

var (
	file_link_proto_rawDescOnce sync.Once
	file_link_proto_rawDescData []byte
)

func file_link_proto_rawDescGZIP() []byte {
	file_link_proto_rawDescOnce.Do(func() {
		file_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)))
	})
	return file_link_proto_rawDescData
}

var file_link_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_link_proto_goTypes = []any{
	(*CreateLinkRequest)(nil),  // 0: pb.CreateLinkRequest
	(*CreateLinkResponse)(nil), // 1: pb.CreateLinkResponse
	(*ListLinksRequest)(nil),   // 2: pb.ListLinksRequest
	(*Link)(nil),               // 3: pb.Link
	(*ListLinksResponse)(nil),  // 4: pb.ListLinksResponse
	(*EnrichLinkRequest)(nil),  // 5: pb.EnrichLinkRequest
	(*EnrichLinkResponse)(nil), // 6: pb.EnrichLinkResponse
	(*UDLinkRequest)(nil),      // 7: pb.UDLinkRequest
	(*UDLinkFields)(nil),       // 8: pb.UDLinkFields
	(*UDLinkResponse)(nil),     // 9: pb.UDLinkResponse
}
var file_link_proto_depIdxs = []int32{
	3, // 0: pb.ListLinksResponse.links:type_name -> pb.Link
	8, // 1: pb.UDLinkRequest.fields:type_name -> pb.UDLinkFields
	3, // 2: pb.UDLinkResponse.link:type_name -> pb.Link
	0, // 3: pb.LinkService.CreateLink:input_type -> pb.CreateLinkRequest
	2, // 4: pb.LinkService.ListLinks:input_type -> pb.ListLinksRequest
	7, // 5: pb.LinkService.UDLink:input_type -> pb.UDLinkRequest
	1, // 6: pb.LinkService.CreateLink:output_type -> pb.CreateLinkResponse
	4, // 7: pb.LinkService.ListLinks:output_type -> pb.ListLinksResponse
	9, // 8: pb.LinkService.UDLink:output_type -> pb.UDLinkResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_link_proto_init() }
func file_link_proto_init() {
	if File_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_proto_rawDesc), len(file_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_link_proto_goTypes,
		DependencyIndexes: file_link_proto_depIdxs,
		MessageInfos:      file_link_proto_msgTypes,
	}.Build()
	File_link_proto = out.File
	file_link_proto_goTypes = nil
	file_link_proto_depIdxs = nil
}
