// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: meeting.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- 모임 생성 ----
type CreateMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMeetingRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateMeetingRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *CreateMeetingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMeetingRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateMeetingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingResponse) Reset() {
	*x = CreateMeetingResponse{}
	mi := &file_meeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingResponse) ProtoMessage() {}

func (x *CreateMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingResponse.ProtoReflect.Descriptor instead.
func (*CreateMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeetingResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

// ---- 모임 목록 조회 (카드) ----
type ListMeetingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeetingsRequest) Reset() {
	*x = ListMeetingsRequest{}
	mi := &file_meeting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetingsRequest) ProtoMessage() {}

func (x *ListMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetingsRequest.ProtoReflect.Descriptor instead.
func (*ListMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{2}
}

func (x *ListMeetingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMeetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetings      []*MeetingCard         `protobuf:"bytes,1,rep,name=meetings,proto3" json:"meetings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMeetingsResponse) Reset() {
	*x = ListMeetingsResponse{}
	mi := &file_meeting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeetingsResponse) ProtoMessage() {}

func (x *ListMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeetingsResponse.ProtoReflect.Descriptor instead.
func (*ListMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{3}
}

func (x *ListMeetingsResponse) GetMeetings() []*MeetingCard {
	if x != nil {
		return x.Meetings
	}
	return nil
}

type MeetingCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingCard) Reset() {
	*x = MeetingCard{}
	mi := &file_meeting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingCard) ProtoMessage() {}

func (x *MeetingCard) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingCard.ProtoReflect.Descriptor instead.
func (*MeetingCard) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{4}
}

func (x *MeetingCard) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *MeetingCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MeetingCard) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *MeetingCard) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *MeetingCard) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

// ---- 모임 단건 조회 (상세) ----
type GetMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{5}
}

func (x *GetMeetingRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetMeetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Images        string                 `protobuf:"bytes,7,opt,name=images,proto3" json:"images,omitempty"` // JSON string (DB: JSONB)
	TotalAmount   int32                  `protobuf:"varint,8,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingResponse) Reset() {
	*x = GetMeetingResponse{}
	mi := &file_meeting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingResponse) ProtoMessage() {}

func (x *GetMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{6}
}

func (x *GetMeetingResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetMeetingResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMeetingResponse) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetMeetingResponse) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetMeetingResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetMeetingResponse) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *GetMeetingResponse) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GetMeetingResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type MeetingMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Images        string                 `protobuf:"bytes,4,opt,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingMember) Reset() {
	*x = MeetingMember{}
	mi := &file_meeting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingMember) ProtoMessage() {}

func (x *MeetingMember) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingMember.ProtoReflect.Descriptor instead.
func (*MeetingMember) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{7}
}

func (x *MeetingMember) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *MeetingMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MeetingMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MeetingMember) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

// ---- 모임 멤버 조회 (상세) ----
type GetMeetingMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingMemberRequest) Reset() {
	*x = GetMeetingMemberRequest{}
	mi := &file_meeting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingMemberRequest) ProtoMessage() {}

func (x *GetMeetingMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingMemberRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingMemberRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{8}
}

func (x *GetMeetingMemberRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetMeetingMemberResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meetingmembers []*MeetingMember       `protobuf:"bytes,1,rep,name=meetingmembers,proto3" json:"meetingmembers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMeetingMemberResponse) Reset() {
	*x = GetMeetingMemberResponse{}
	mi := &file_meeting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingMemberResponse) ProtoMessage() {}

func (x *GetMeetingMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingMemberResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingMemberResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{9}
}

func (x *GetMeetingMemberResponse) GetMeetingmembers() []*MeetingMember {
	if x != nil {
		return x.Meetingmembers
	}
	return nil
}

// ---- 초대 ----
type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_meeting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{10}
}

func (x *CreateInviteRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type CreateInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteUrl     string                 `protobuf:"bytes,1,opt,name=inviteUrl,proto3" json:"inviteUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_meeting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{11}
}

func (x *CreateInviteResponse) GetInviteUrl() string {
	if x != nil {
		return x.InviteUrl
	}
	return ""
}

type JoinByInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteRequest) Reset() {
	*x = JoinByInviteRequest{}
	mi := &file_meeting_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteRequest) ProtoMessage() {}

func (x *JoinByInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteRequest.ProtoReflect.Descriptor instead.
func (*JoinByInviteRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{12}
}

func (x *JoinByInviteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinByInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteResponse) Reset() {
	*x = JoinByInviteResponse{}
	mi := &file_meeting_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteResponse) ProtoMessage() {}

func (x *JoinByInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteResponse.ProtoReflect.Descriptor instead.
func (*JoinByInviteResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{13}
}

func (x *JoinByInviteResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type UDMeetingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 필수 (빈값 불허)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 필수: "u" | "d"
	Op string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	// op=="u" 일 때만 사용
	Fields        *UDMeetingFields `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDMeetingRequest) Reset() {
	*x = UDMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDMeetingRequest) ProtoMessage() {}

func (x *UDMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDMeetingRequest.ProtoReflect.Descriptor instead.
func (*UDMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{14}
}

func (x *UDMeetingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDMeetingRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDMeetingRequest) GetFields() *UDMeetingFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 부분 업데이트용 필드 묶음
// 규칙(서버):
// - 필드가 존재하지 않으면: 변경 안 함
// - 필드가 존재하지만 ""(빈문자)면: 변경 안 함 (요구사항 반영)
// - 날짜는 "YYYY-MM-DD"일 때만 반영, ""면 무시
type UDMeetingFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Images        string                 `protobuf:"bytes,6,opt,name=images,proto3" json:"images,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDMeetingFields) Reset() {
	*x = UDMeetingFields{}
	mi := &file_meeting_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDMeetingFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDMeetingFields) ProtoMessage() {}

func (x *UDMeetingFields) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDMeetingFields.ProtoReflect.Descriptor instead.
func (*UDMeetingFields) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{15}
}

func (x *UDMeetingFields) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UDMeetingFields) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UDMeetingFields) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *UDMeetingFields) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UDMeetingFields) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UDMeetingFields) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

type UDMeetingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 항상 id 반환
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// "u" or "d"
	Op string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	// update인 경우 최신 스냅샷(선택)
	Meeting       *GetMeetingResponse `protobuf:"bytes,3,opt,name=meeting,proto3" json:"meeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDMeetingResponse) Reset() {
	*x = UDMeetingResponse{}
	mi := &file_meeting_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDMeetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDMeetingResponse) ProtoMessage() {}

func (x *UDMeetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDMeetingResponse.ProtoReflect.Descriptor instead.
func (*UDMeetingResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{16}
}

func (x *UDMeetingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UDMeetingResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UDMeetingResponse) GetMeeting() *GetMeetingResponse {
	if x != nil {
		return x.Meeting
	}
	return nil
}

type SetTotalAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTotalAmountRequest) Reset() {
	*x = SetTotalAmountRequest{}
	mi := &file_meeting_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTotalAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTotalAmountRequest) ProtoMessage() {}

func (x *SetTotalAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTotalAmountRequest.ProtoReflect.Descriptor instead.
func (*SetTotalAmountRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{17}
}

func (x *SetTotalAmountRequest) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SetTotalAmountRequest) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type SetTotalAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	MemberCount   int32                  `protobuf:"varint,3,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	PerPerson     int32                  `protobuf:"varint,4,opt,name=perPerson,proto3" json:"perPerson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTotalAmountResponse) Reset() {
	*x = SetTotalAmountResponse{}
	mi := &file_meeting_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTotalAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTotalAmountResponse) ProtoMessage() {}

func (x *SetTotalAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTotalAmountResponse.ProtoReflect.Descriptor instead.
func (*SetTotalAmountResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{18}
}

func (x *SetTotalAmountResponse) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SetTotalAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *SetTotalAmountResponse) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *SetTotalAmountResponse) GetPerPerson() int32 {
	if x != nil {
		return x.PerPerson
	}
	return 0
}

var File_meeting_proto protoreflect.FileDescriptor

const file_meeting_proto_rawDesc = "" +
	"\n" +
	"\rmeeting.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\"\xbf\x01\n" +
	"\x14CreateMeetingRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x05 \x01(\tR\tthumbnail\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"5\n" +
	"\x15CreateMeetingResponse\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\".\n" +
	"\x13ListMeetingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x14ListMeetingsResponse\x12+\n" +
	"\bmeetings\x18\x01 \x03(\v2\x0f.pb.MeetingCardR\bmeetings\"\x99\x01\n" +
	"\vMeetingCard\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1c\n" +
	"\tthumbnail\x18\x05 \x01(\tR\tthumbnail\"1\n" +
	"\x11GetMeetingRequest\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\"\xfc\x01\n" +
	"\x12GetMeetingResponse\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06images\x18\a \x01(\tR\x06images\x12 \n" +
	"\vtotalAmount\x18\b \x01(\x05R\vtotalAmount\"q\n" +
	"\rMeetingMember\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06images\x18\x04 \x01(\tR\x06images\"7\n" +
	"\x17GetMeetingMemberRequest\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\"U\n" +
	"\x18GetMeetingMemberResponse\x129\n" +
	"\x0emeetingmembers\x18\x01 \x03(\v2\x11.pb.MeetingMemberR\x0emeetingmembers\"3\n" +
	"\x13CreateInviteRequest\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\"4\n" +
	"\x14CreateInviteResponse\x12\x1c\n" +
	"\tinviteUrl\x18\x01 \x01(\tR\tinviteUrl\"+\n" +
	"\x13JoinByInviteRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"4\n" +
	"\x14JoinByInviteResponse\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\"_\n" +
	"\x10UDMeetingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12+\n" +
	"\x06fields\x18\x03 \x01(\v2\x13.pb.UDMeetingFieldsR\x06fields\"\xb9\x01\n" +
	"\x0fUDMeetingFields\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x16\n" +
	"\x06images\x18\x06 \x01(\tR\x06images\"e\n" +
	"\x11UDMeetingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x120\n" +
	"\ameeting\x18\x03 \x01(\v2\x16.pb.GetMeetingResponseR\ameeting\"W\n" +
	"\x15SetTotalAmountRequest\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12 \n" +
	"\vtotalAmount\x18\x02 \x01(\x05R\vtotalAmount\"\x98\x01\n" +
	"\x16SetTotalAmountResponse\x12\x1c\n" +
	"\tmeetingId\x18\x01 \x01(\tR\tmeetingId\x12 \n" +
	"\vtotalAmount\x18\x02 \x01(\x05R\vtotalAmount\x12 \n" +
	"\vmemberCount\x18\x03 \x01(\x05R\vmemberCount\x12\x1c\n" +
	"\tperPerson\x18\x04 \x01(\x05R\tperPerson2\xe3\x06\n" +
	"\x0eMeetingService\x12a\n" +
	"\rCreateMeeting\x12\x18.pb.CreateMeetingRequest\x1a\x19.pb.CreateMeetingResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/meetings\x12j\n" +
	"\fListMeetings\x12\x17.pb.ListMeetingsRequest\x1a\x18.pb.ListMeetingsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/meetings/list/{user_id}\x12a\n" +
	"\n" +
	"GetMeeting\x12\x15.pb.GetMeetingRequest\x1a\x16.pb.GetMeetingResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/meetings/{meetingId}\x12{\n" +
	"\x10GetMeetingMember\x12\x1b.pb.GetMeetingMemberRequest\x1a\x1c.pb.GetMeetingMemberResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/meetings/members/{meetingId}\x12q\n" +
	"\fCreateInvite\x12\x17.pb.CreateInviteRequest\x1a\x18.pb.CreateInviteResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/meetings/{meetingId}/invite\x12c\n" +
	"\fJoinByInvite\x12\x17.pb.JoinByInviteRequest\x1a\x18.pb.JoinByInviteResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/meetings/join\x12X\n" +
	"\tUDMeeting\x12\x14.pb.UDMeetingRequest\x1a\x15.pb.UDMeetingResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/meetings/ud\x12p\n" +
	"\x0eSetTotalAmount\x12\x19.pb.SetTotalAmountRequest\x1a\x1a.pb.SetTotalAmountResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/meetings/totalAmountB\x17Z\x15WEPLAN/internal/pb;pbb\x06proto3"

var (
	file_meeting_proto_rawDescOnce sync.Once
	file_meeting_proto_rawDescData []byte
)

func file_meeting_proto_rawDescGZIP() []byte {
	file_meeting_proto_rawDescOnce.Do(func() {
		file_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meeting_proto_rawDesc), len(file_meeting_proto_rawDesc)))
	})
	return file_meeting_proto_rawDescData
}

var file_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_meeting_proto_goTypes = []any{
	(*CreateMeetingRequest)(nil),     // 0: pb.CreateMeetingRequest
	(*CreateMeetingResponse)(nil),    // 1: pb.CreateMeetingResponse
	(*ListMeetingsRequest)(nil),      // 2: pb.ListMeetingsRequest
	(*ListMeetingsResponse)(nil),     // 3: pb.ListMeetingsResponse
	(*MeetingCard)(nil),              // 4: pb.MeetingCard
	(*GetMeetingRequest)(nil),        // 5: pb.GetMeetingRequest
	(*GetMeetingResponse)(nil),       // 6: pb.GetMeetingResponse
	(*MeetingMember)(nil),            // 7: pb.MeetingMember
	(*GetMeetingMemberRequest)(nil),  // 8: pb.GetMeetingMemberRequest
	(*GetMeetingMemberResponse)(nil), // 9: pb.GetMeetingMemberResponse
	(*CreateInviteRequest)(nil),      // 10: pb.CreateInviteRequest
	(*CreateInviteResponse)(nil),     // 11: pb.CreateInviteResponse
	(*JoinByInviteRequest)(nil),      // 12: pb.JoinByInviteRequest
	(*JoinByInviteResponse)(nil),     // 13: pb.JoinByInviteResponse
	(*UDMeetingRequest)(nil),         // 14: pb.UDMeetingRequest
	(*UDMeetingFields)(nil),          // 15: pb.UDMeetingFields
	(*UDMeetingResponse)(nil),        // 16: pb.UDMeetingResponse
	(*SetTotalAmountRequest)(nil),    // 17: pb.SetTotalAmountRequest
	(*SetTotalAmountResponse)(nil),   // 18: pb.SetTotalAmountResponse
}
var file_meeting_proto_depIdxs = []int32{
	4,  // 0: pb.ListMeetingsResponse.meetings:type_name -> pb.MeetingCard
	7,  // 1: pb.GetMeetingMemberResponse.meetingmembers:type_name -> pb.MeetingMember
	15, // 2: pb.UDMeetingRequest.fields:type_name -> pb.UDMeetingFields
	6,  // 3: pb.UDMeetingResponse.meeting:type_name -> pb.GetMeetingResponse
	0,  // 4: pb.MeetingService.CreateMeeting:input_type -> pb.CreateMeetingRequest
	2,  // 5: pb.MeetingService.ListMeetings:input_type -> pb.ListMeetingsRequest
	5,  // 6: pb.MeetingService.GetMeeting:input_type -> pb.GetMeetingRequest
	8,  // 7: pb.MeetingService.GetMeetingMember:input_type -> pb.GetMeetingMemberRequest
	10, // 8: pb.MeetingService.CreateInvite:input_type -> pb.CreateInviteRequest
	12, // 9: pb.MeetingService.JoinByInvite:input_type -> pb.JoinByInviteRequest
	14, // 10: pb.MeetingService.UDMeeting:input_type -> pb.UDMeetingRequest
	17, // 11: pb.MeetingService.SetTotalAmount:input_type -> pb.SetTotalAmountRequest
	1,  // 12: pb.MeetingService.CreateMeeting:output_type -> pb.CreateMeetingResponse
	3,  // 13: pb.MeetingService.ListMeetings:output_type -> pb.ListMeetingsResponse
	6,  // 14: pb.MeetingService.GetMeeting:output_type -> pb.GetMeetingResponse
	9,  // 15: pb.MeetingService.GetMeetingMember:output_type -> pb.GetMeetingMemberResponse
	11, // 16: pb.MeetingService.CreateInvite:output_type -> pb.CreateInviteResponse
	13, // 17: pb.MeetingService.JoinByInvite:output_type -> pb.JoinByInviteResponse
	16, // 18: pb.MeetingService.UDMeeting:output_type -> pb.UDMeetingResponse
	18, // 19: pb.MeetingService.SetTotalAmount:output_type -> pb.SetTotalAmountResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_meeting_proto_init() }
func file_meeting_proto_init() {
	if File_meeting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_proto_rawDesc), len(file_meeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_proto_goTypes,
		DependencyIndexes: file_meeting_proto_depIdxs,
		MessageInfos:      file_meeting_proto_msgTypes,
	}.Build()
	File_meeting_proto = out.File
	file_meeting_proto_goTypes = nil
	file_meeting_proto_depIdxs = nil
}
